### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by kevinb1003** [caffedrine/scaleway-whmcs#2]
Hey,
I need your help

**Comment by caffedrine** [comment]
I have received your emails. Guys from 1WAY contacted me too to write full documentation for this module.
I will write full documentation these days which will guide you, depending on how time allow me to do this!

**Comment by kevinb1003** [comment]
Can you tell me the right custom field?
Thanks.

**Comment by caffedrine** [comment]
Custom field for what? You didn't specified what is your problem you requested help for.

**Comment by kevinb1003** [comment]
In the other issue you write: Don't forget to complete "Commercial type" and "Admin username" fields too as those are required in order for this plugin to work.

P.S: I have the same issue of the other guy

**Comment by caffedrine** [comment]
Oh, I understand!
For visitors, the other issue is: https://github.com/caffedrine/scaleway-whmcs/issues/1

1. Token field. This field must be filled with Access Token, provided by Scaleway. 
Login to Scaleway then go to: https://cloud.scaleway.com/#/credentials
Create New Token >> copy the token you just created into the field specified above

2. You have to know that, for every package provided by Scaleway, you'll have to create a separate product inside your WHMCS Products/Services.
And the packages provided by Scaleway, are the following (updated Oct 2015):
>                 'C1' => 'C1 - ARM_4DC_2GB',
>                 'C2S' => 'C2S - x86_4DC_8GB',    //Dedicated Servers
>                 'C2M' => 'C2M - x86_8DC_16GB',
>                 'C2L' => 'C2L - x86_8DC_32GB',
>                 'VC1S' => 'VC1S - x86_2SC_2GB',  //VPS Servers
>                 'VC1M' => 'VC1M - x86_4SC_4GB',
>                 'VC1L' => 'VC1L - x86_6SC_8GB',

 To provide all Scaleway packages, you'll have to create a separate product for ever package. Specifically, create a new product with Commercial Type C1, another product with commercial type C2S and so on.

If you want to provide only ARM based arch servers, then create a single product with C1 chosen on Commercial Type field.

3. In order to update data inside WHMCS Panel, the module require the username of an active with full privileges administrator (Check WHMCS API docs if you want to understand more). So, fill this field with an active administrator nickname.

4. IPv6. Check this if you want to enable IPv6 on that product.
PS: Check Scaleway to see if it is supported for selected Commercial Type desired.

5. Scaleway SSH Key (Putty format [.ppk])
This field should be filled in the following format:

> `PuTTY-User-Key-File-2: ssh-rsa
> Encryption: none
> Comment: ScaleWay
> Public-Lines: 6
> AAAAB3NzaC1yc2EAAAABJQAAAQEAzacjaGdQVnmuNDNtGI8xT+xGAHb
> .........................................................
> 1fIKv9JwqKZwyBc3oDDvnjq4IBDFuszNOlricjNWMpL4JAeEZQ==
> Private-Lines: 14
> AAABACFZX7AQwPkODdzhgu2f4DmlUco5caNyHFNpuwHvfFaB/eVRToEE9
> ..........................................................
> L/s2xmUkxcxyop+MmKAn/nTm1k4NO3cZa9S3O9QYuYglCA==
> Private-MAC: affe529e88b4b974cc6ee321737fd47c7208c720`

What is this field for? As you may know, the new servers created by Scaleway does not have a root password set; so you can only login with a SSH KAy, actually the SAME ssh key. Assuming that you want to resell those server, you may not want to create all servers with same SSH key then send same SSH Key to different clients. So, script login to server, remove old SSH Key and setup a new random password. This option should work on all Debian based distributions. I have not tested for the others...

PS: The key should be set on Scaleway control panel too. Otherwise it will not work.

Stay connected, those days I will write fill documentation :)

**Comment by kevinb1003** [comment]
So let's waiting..
Thanks dude!

**Comment by ProTechEx** [comment]
I am the Guy who contact you from your Page,
I look forward to the full documentation.

I have some question in upfront:
1. Is it required to add "Server" or "Server Group" in WHMCS (Setup > Products/Services > Server), i yes what exatly need to to here ?
2. What is need to select, if we add the Scaleway packages (Servers like "C2L" ) in to WHMCS "Products/Services" on the Field "Product Type" & "Product Group" ??
3. On Product (Server) order, there some Fields, like "ns1" "ns2" "root password" etc.
  How can the clients get option, which Linux distribution they want use, i've missing all the configuration options that on Scaleway avalible for the Clients.  Are those options on your addon also avalible on the Client Area ?
4. I get the Error Message, once the WHMCS try to Create the Service:
**Error 404: not found 404 not found 404 not found 404 not found, what are you looking for?**

Could you add me on Skype: pro-tech-ex

Thanks nd kind regards

**Comment by caffedrine** [comment]
Guys, check this out: https://github.com/caffedrine/scaleway-whmcs/wiki/Setting-up-module

**Comment by ProTechEx** [comment]
Hey Cafeedrine,

big Thanks m8 ;)
